### ISSUE TITLE
Add optional player count graph

### ISSUE THREAD

**Issue by nralbrecht** [WeLoveSquad/squad-server-info-discord-bot#4]
A optional section should be added to the server embed. If wanted a graph with the player count history for the last 24 hours should be shown.

The BattleMetrics endpoint `GET /servers/{server_id}/player-count-history` can be used to fetch the data required to render an image.

See following example provided by *[RPP] GHOTI*:
![Example](https://cdn.discordapp.com/attachments/832606807595155476/1064526629516361738/image.png)

**Comment by Mikerosoft25** [comment]
Not planned atm
